Lab10/urls.py
from django.conf.urls import url
from .views import subscribe, validation, unsubscribe, login, my_view
app_name = "Lab10"

urlpatterns = [
	url(r'subscribe/$', subscribe, name = 'subscribe'),
	url(r'validation/$', validation, name = 'validation'),
	url(r'unsubscribe/$', unsubscribe, name = 'unsubscribe'),
	url(r'log-in/$', login, name = 'login'),
	url(r'success/$', my_view, name = 'success'),
	
]

Lab6/urls.py
from django.conf.urls import url
from .views import index, add_status, show_profile, get_book_list, show_book_list, logout

app_name = "Lab6"
urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'my-status/$', add_status, name = 'my-status'),
	url(r'my-profile/$', show_profile, name = 'my-profile'),
	url(r'book-list/$', show_book_list, name = 'book-list'),
	url(r'BookListInJson/$', get_book_list, name = 'book-list-json'),
	url(r'logout/$', logout, name = 'logout'),
	# url(r'data-json/$', get_book_list, name = 'data-json'),
	# url('mydiary/', mydiary, name = 'mydiary'),
	
	
]

NewLabPPW/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path

import Lab6.urls as Lab6
import Lab10.urls as Lab10

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^lab-6/', include(Lab6, namespace = 'lab-6')),
    url(r'^lab-10/', include(Lab10, namespace = 'lab-10')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

Lab10/models.py
from django.db import models

class Subscribe(models.Model):
	email=models.EmailField(unique=True)
	name=models.CharField(max_length=50)
	password=models.CharField(max_length=30)

Lab6/models.py
from django.db import models
from django import forms
from django.utils import timezone
from datetime import datetime, date

class Status(models.Model):
	my_status = models.TextField(max_length=300)
	time = models.DateTimeField(default=timezone.now)

Lab10/forms.py
from django import forms
from .models import Subscribe

class SubscribeForm(forms.ModelForm):
	email = forms.CharField(widget=forms.TextInput(attrs={
		'type'			: 'email',
		'class'			: 'form-control',
		'placeholder'	: 'Email',
		'id'			: 'email_field',
	}))	
	
	name = forms.CharField(widget=forms.TextInput(attrs={
		'class'			: 'form-control',
		'placeholder'	: 'Name',
		'id'			: 'name_field',
	}), max_length=50)	
	
	password = forms.CharField(widget=forms.TextInput(attrs={
		'type'			: 'password',
		'class'			: 'form-control',
		'placeholder'	: 'Password',
		'id'			: 'pass_field',
	}), max_length=30)
	
	class Meta:
		model = Subscribe
		fields = ['email', 'name', 'password']

Lab6/forms.py
from django import forms
from django.forms import ModelForm
from .models import Status

class status_form(forms.ModelForm):
	
	error_messages = {
		'required': 'Please fill this field',
	}
		
	status_attrs = {
		'type': 'text',
		'cols': 50,
		'rows': 4,
		'placeholder':'Type your status here'
	}
	my_status = forms.CharField(label = '', required = True, max_length = 300, widget = forms.Textarea(attrs = status_attrs))

	class Meta:
		model = Status
		fields = ['my_status']

Lab10/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.core import serializers
from .forms import SubscribeForm
from .models import Subscribe
import requests, json, re

from django.contrib.auth import authenticate, login

@csrf_exempt
def subscribe(request):
	data = []
	if request.method == "POST":
		form = SubscribeForm(request.POST or None)
		email = request.POST['email']
		name = request.POST['name']
		password = request.POST['password']
		filter_email = Subscribe.objects.filter(email=email)
		if (len(filter_email) > 0):
			response_message = 'Email has been taken.'
		else:
			new_subscriber = Subscribe(email=email, name=name, password=password)
			new_subscriber.save()
	else:
		form = SubscribeForm()
	return render(request, 'subscribe.html', {'form': form})
	
@csrf_exempt
def unsubscribe(request):
	subId = request.POST['id']
	Subscribe.objects.filter(id=subId).delete()
	return HttpResponse(json.dumps({'message': "Errrr, something goes wrong.."}),
									content_type="application/json")

def model_to_dict(obj):
	data = serializers.serialize('json',[obj,])
	struct = json.loads(data)
	data = json.dumps(struct[0]["fields"])
	return data
								
@csrf_exempt
def validation(request):
	email_validation= False
	name_validation= False
	password_validation= False
	
	if request.method == "POST":
		email = request.POST['email']
		name = request.POST['name']
		password = request.POST['password']
		
		if 5 <= len(name) <= 50:
			name_validation = True
			
		if len(email) >= 2:
			email_validation = bool(re.match("^.+@(\[?)[a-zA-Z0-9-.]+.([a-zA-Z]{2,3}|[0-9]{1,3})(]?)$", email))
			
		if 8 <= len(password) <= 30:
			password_validation = True
			
		if not name_validation:
			return HttpResponse(json.dumps({'message': 'Please lengthen your name to 5 characters and less than 50.'}), 
											content_type="application/json")
			
		if not email_validation:
			return HttpResponse(json.dumps({'message': 'Please write your email correctly.'}), 
											content_type="application/json")
			
		filter_email = Subscribe.objects.filter(email=email)
		if len(filter_email) > 0:
			return HttpResponse(json.dumps({'message': 'Email has been taken..'}), 
											content_type="application/json")
			
		if not password_validation:
			return HttpResponse(json.dumps({'message': 'Please lengthen your password to 8 characters and less than 30.'}), 
											content_type="application/json")
			
		return HttpResponse(json.dumps({'message': 'Your datas are valid!'}), 
										content_type="application/json")
		
	else:
		return HttpResponse(json.dumps({'message': "ciye error"}), 
							content_type="application/json")
							
def login (request):
	return render(request, 'log_in.html')

def my_view(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(request, username=username, password=password)
	if user is not None:
		login(request, user)
		return render(request, 'book_list.html')
	else:
		return render(request, 'log_in.html')
		

Lab6/views.py
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext, loader
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth import logout as oauth_logout
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from .models import Status
from .forms import status_form
import datetime, pytz, json, requests

response = {}
def index(request):
    response['author'] = "Adelia Utami"
    stat = Status.objects.all()
    response['stat'] = stat
    html = 'landing_page.html'
    response['stat_form'] = status_form
    return render(request, html, response)

def add_status(request):
    form = status_form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        stat = Status(my_status=request.POST['my_status'])
        stat.save()
        return HttpResponseRedirect('/lab-6/')
    else:
        return HttpResponseRedirect('/lab-6/')
		
# @csrf_exempt	
# def mydiary(request):
	# tgl = request.POST['tgl']
	# catatan = request.POST['catatan']
	# diary = Status.objects.create(tgl = tgl, catatan = catatan)
	# diary.save()
	# json = JsonResponse( {"tgl":tgl,"catatan":catatan}, safe=False )
	# return json
	
def show_profile(request):
    return render(request, "profile.html")

def get_book_list(request):
	get_json = requests.get('https://www.googleapis.com/books/v1/volumes?q=quilting')
	return HttpResponse(get_json, content_type = 'BookListInJson')	
	
def show_book_list(request):
    return render(request, "book_list.html")
	
def logout(request):
	oauth_logout(request)
	return redirect('/lab-6/book-list/')

Lab10/templates/log_in.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">	
	<div class="row">
	<h2><strong>Log In Here </strong></h2>
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<!-- Start form -->
                    <form>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Username</label>
                        <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Enter email">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                      </div>
                      <div class="form-check">
                        <button type="submit" class="btn btn-primary">Log in</button>
                      </div>
                    </form>
			<!-- End form -->
		</div>
	</div>
</div>

Lab10/templates/subscribe.html
{% load static %}
{% load staticfiles %}

<head>
	<meta charset="utf-8" name="viewport" content="width = device-width, initial-scale = 1.0">
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="{% static 'ajaxQ.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'cssQ.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

{% block content %}
<body>
	
	<!-- <div id="load"></div> -->
	<div id="begron" class="bg"></div>
	<br><h2><center><b>Subscribe Me!</b></center></h2>		
	
	<div class="container">
		<div id="response_message"></div> 
		<form class="form-group" id="sub_form" method="POST" onsubmit="return false;">
			{% csrf_token %} 
			{% for field in form %}
				{{ field.label }} : {{ field }}
			{% endfor %}
			<div id="validation_message"></div>
			<br><input class="btn" id="sub_btn" type="submit" value="Subscribe" disabled onclick="subscribe()"/>
		</form>
		<a class="btn btn-outline-dark" href="/lab-6/" role="button">Back to Home</a>
	</div>
	
	<div class="container">
		<br><h2><center><b>Subscriber List</b></center></h2>
		<div class="flex">
			<table id="sub-table" class="table table-hover table-striped" style="text-align: justify">
				<thead>
					<tr>
						<th scope="col">Name</th>
						<th scope="col">Email</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
	
</body>
{% endblock %}

Lab6/templates/book_list.html
{% load static %}
{% load staticfiles %}
{% include 'navbar.html' %}

<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8" name="viewport" content="width = device-width, initial-scale = 1.0">
		<link rel="stylesheet" type="text/css" href="{% static 'cssQ.css' %}">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
		
		<script src="{% static 'jsQ.js' %}"></script>
		
		<!-- Add icon library -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		
	</head>
	
	{% block content %}
	<body>
		<style>
		.is-favorited {
			animation:effect 0.8s infinite;
			color:#ffbf00;
		}
		</style>
		
		<div id="load"></div>
		<div id="begron" class="bg"></div>
				
		<center>
			<br><h2><b>Book List</b></h2>	
			{% if user.is_authenticated %}
				<h4>Selamat Datang {{ user.username }}! <a href="{% url 'Lab6:logout' %}" type="button" class="btn btn-danger">Logout </a></h4>
			{% else %}
				<a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-danger btn-block" style="width:180px"><i class="fa fa-google"></i> | Login with <b>Google</b></a>	
			{% endif %}
		</center>
		
		<div><center>
			<br><h5><center>Choose the keyword</center></h5>	
			{% csrf_token %}
			<button type="button" class="btn btn-outline-dark" id="happy">Happy</button>
			<button type="button" class="btn btn-outline-dark" id="sleep">Sleep</button>
			<button type="button" class="btn btn-outline-dark" id="quilting">Quilting</button>
			</center>
		</div>
		
		<div class="container">
			<p>Favourited Book(s) : <input id = "total-fav" class="btn btn-outline-secondary" type="button" value="0"></p>
			<div class="flex">
					<table id="book-table" class="table table-hover table-striped" style="text-align: justify">
						<thead>
							<tr>
								<th scope="col">Title</th>
								<th scope="col">Cover</th>
								<th scope="col">Description</th>
								<th scope="col">Authors</th>
								<th scope="col">Publisher</th>
								<th scope="col">Fav</th>
							</tr>
						</thead>
					</table>
			</div>
		</div>
	
	</body>
	{% endblock %}
	
</html>

Lab6/templates/landing_page.html
{% load static %}
{% load staticfiles %}
{% include 'navbar.html' %}

<head>
	<meta charset="utf-8" name="viewport" content="width = device-width, initial-scale = 1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'cssQ.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="{% static 'jsQ.js' %}"></script>
</head>

	{% block content %}
	<body>
		<div id="load"></div>
		<div id="begron" class="bg"></div>
		<br><h2><center><b>Hello, Apa kabar? :)</b></center></h2>		
		
		<center>
			<form id="form" method="POST" action="{% url 'Lab6:my-status' %}">
					{% csrf_token %}
					{{ stat_form.as_p }}
					<button type='submit' class='btn'>Post</button>
					<br>
			</form>
		</center>
		
		<section name="my-list" id="my-list">
			<div class="container">
				<h2 class="my-list-title"><center><b>My Status</b></center></h2>
				<div class="flex">
					{% if stat %}
						<table class="table table-hover table-striped" align="center" style="text-align: center">
							<thead>
								<tr>
									<th scope="col">Time</th>
									<th scope="col">Status</th>
								</tr>
							</thead>
							{% for data in stat %}
								<tr>
									<td scope="row">{{ data.time }}</td>
									<td scope="row">{{ data.my_status }}</td>
								</tr>
							{% endfor %}
						</table>
					{% else %}
					<div class="alert text-center">
						<h4><center>---No Available Status---</center></h4>
					</div>
					{% endif %}
				</div>
			</div>
		</section>
	</body>
{% endblock %}

Lab6/templates/navbar.html
{% load static %}
{% block content %}

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'cssQ.css' %}">
	<title>adeliaut</title>

</head>

<nav id="navbarQ" style="font-family:helvetica; padding-right: 70%;" class="navbar navbar-expand-lg sticky-top navbar-light navbar-style">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
		<div class="container">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="/lab-6/"><b>HOME</b></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="my-profile/"><b>PROFILE</b></a>
				</li>				
				<li class="nav-item">
					<a class="nav-link" href="book-list/"><b>BOOKS</b></a>
				</li>
				<li class="nav-item">
					<a id="theme" class="nav-link" href="#"><b>THEME</b></a>
				</li>
			</ul>
		</div>
	</div>		
</nav>
	
{% endblock %}

Lab6/templates/profile.html
{% load static %}
{% load staticfiles %}
{% include 'navbar.html' %}

<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8" name="viewport" content="width = device-width, initial-scale = 1.0">
		<link rel="stylesheet" type="text/css" href="{% static 'cssQ.css' %}">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="{% static 'jsQ.js' %}"></script>
	</head>
		
	<body>
		<div id="load"></div>
		<div id="begron" class="bg"></div>
		
		<div class="table-responsive">
			<article class="about-me" align="justify">
			<h2><b>About Me
				<a class="btn btn-outline-dark" href="/lab-10/subscribe/" role="button">Click here to subscribe!</a>
			</b></h2>
			<table class="table table-borderless">
				<tr>
					<td align="center" width="350"><img class="img-about-me img-fluid" src="https://lh3.google.com/u/0/d/1pVWOB_Bn4LGDV1UNC3YEctWko4ZJ6EWU=w1920-h915-iv1" alt="Adelia Utami"; width=300px; height=300px></td>
					<td align="justify"><p>Hello World! My name is Adelia Utami, known as Adel, currently studying as a System Information student in University of Indonesia. I love to spend my time with my family and create delightful moments with them. I like to keep things clean and neat. I am a cheerful, loyal, and trustworthy person.</p></td>
				</tr>
				
			</table>
		</div>
		
		<br>
		
		<div class="table-responsive">
			<article class="edu">
			<h2><b>Education</b></h2>
			<table class="table table-borderless">
				<tbody>
					<tr>
						<th scope="row"></th>
						<td class="text-center"><img class="img-fluid center-block" src="https://lh3.google.com/u/0/d/1S1IDDGLx_2XGOynAZt8OKYlu3aG9QFkF=w1087-h891-iv1" alt="UI"; width=150px; height=150px></td>
						<td class="text-center"><img class="img-fluid center-block" src="https://lh3.google.com/u/0/d/1vybDeBZZPWsB1w6vgshxppiXrEse0BzF=w1087-h891-iv1" alt="Bonlap"; width=165px; height=165px></td>
						<td class="text-center"><img class="img-fluid center-block" src="https://lh3.google.com/u/0/d/1pSIGK5qdEpdfpjJtN_0IFEc-j0b58cOs=w1087-h891-iv1" alt="Litam"; width=150px; height=150px></td>  
						<td class="text-center"><img class="img-fluid center-block" src = "https://lh3.google.com/u/0/d/13L_5qsDG86DntEX8i4AUP9snLRyyQY4i=w1087-h891-iv1" alt="Jasut"; width=150px; height=150px></td>
					</tr>
					
					<tr>
					  <th scope="row"></th>
					  <td class="text-center"><h4><b>2017 - now</b></h4></td>
					  <td class="text-center"><h4><b>2014 - 2017</b></h4></td>
					  <td class="text-center"><h4><b>2011 - 2014</b></h4></td>
					  <td class="text-center"><h4><b>2005 - 2011</b></h4></td>
					</tr>
					
					<tr>
					  <th scope="row"></th>
					  <td class="text-center"><h4>Universitas Indonesia</h4></td>
					  <td class="text-center"><h4>SMAN 1 Tambun Selatan</h4></td>
					  <td class="text-center"><h4>SMPN 5 Tambun Selatan</h4></td>
					  <td class="text-center"><h4>SD Jaya Suti Abadi</h4></td>
					</tr>
				</tbody>
			</table>
		</div>
 
		<!-- Accordion JQuery -->
		<!-- source code: https://codepen.io/EmmaJD/pen/yQBQdQ?page=1 -->
		<div id="main">
			<div  id="akord1"class="accordion">
				<div class="accordion-title">
					<h4 class="secondary"><b>ACTIVITY LIST</b></h4>
				</div>
				
				<div class="accordion-text">
					<li>2nd Programming Assignment SDA in progress</li>
					<li>8th Story PPW in progress</li>
					<li>Prototype for business proposal in progress</li>
				</div>				
			</div>
			
			<div id="akord2" class="accordion">
				<div class="accordion-title">
					<h4 class="secondary"><b>EXPERIENCE</b></h4>
				</div>
				
				<div class="accordion-text">
					<li>(2014 - 2017) <b>Bonlap English Club</b>: As a general active member </li>
					<li>(2016) <b>MnG Bonlap English Club</b>: As a vice project officer</li>
					<li>(2017 - now) <b>BEM Fasilkom UI 2018</b>: As a secretariat division member</li>
					<li>(2017 - now) <b>FUKI Fasilkom UI 2018</b>: As a syiar departement member</li>
					<li>(2018) <b>PMB Fasilkom UI 2018</b>: As an academic staff</li>
					<li>(2018) <b>SIWAK NG 2018</b>: As a person in charge of consumption</li>
				</div>
			</div>
			
			<div id="akord3" class="accordion">
				<div class="accordion-title">
					<h4 class="secondary"><b>ACHIEVEMENT</b></h4>
				</div>
			
				<div class="accordion-text" align="center" >
					<img src="https://lh3.google.com/u/0/d/1bDI5i4Byj_c7nI_FQk-N8iF5l-jT12Tq=w1920-h915-iv1">
				</div>
			</div>
		</div>

	</body>
</html>